### ISSUE TITLE
Discord CDN からの直リンクについて

### ISSUE THREAD

**Issue by Sasakura-ayato** [Budobudou/GenkaiyaBot#12]
# 概要

現在の仕様では、画像の送信に関し Discord から直リンクを行っている

# 問題点
- 正規決定ではないものの、Discord CDN からの直リンクは推奨しかねるという会話ログがある
- 画像のライセンス明記しにくい
- Discord サーバーを常に利用するということなので、何らかの仕様変更（一定期間以上過去のデータは削除するなど。Slack などで見られる）に対して耐えられない
- 意図していない Discord CDN の利用なので、あまり良い行動ではない

**Comment by NekokawaNanami** [comment]
すべてGoogleDriveに移すのはどうでしょうか

**Comment by Sasakura-ayato** [comment]
Google Drive もあれ直リンクは URL 仕様の変更が起きるんですよね（Brain Wiki で発生していた気がする）

**Comment by Sasakura-ayato** [comment]
一番いいのは assets として GitHub にアップロードかなと思っているんですけど

**Comment by Budobudou** [comment]
そうですね。
GitHub にアップロードしようと思います。

**Comment by Budobudou** [comment]
この前、
GitHub にアップロードすると言ってましたが、
ライセンス的にアレなのでimgur にアップロードしようかと思います。
